### AWS ###
# This profile is for live production and uses a live AWS MySQL database

server:
  port: 5000

spring:

  profiles:
    profile-name: AWS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    database:
      name: WILMA_DB
      host: aussie-db.cjdfjxus4vpw.ap-southeast-2.rds.amazonaws.com
      port: 3306
    url: jdbc:mysql://${spring.datasource.database.host}:${spring.datasource.database.port}/${spring.datasource.database.name}
    username: WILMA_USER
    password: WILMA_P455W0RD
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
hibernate:
  format_sql: true