### Common ###
module:
  name: WEB

spring:
  application:
    name: Work Integrated Learning Management Application - WILMA

  profiles:
    active: dev # Set this as either dev or prod

api:
  v1.context-path: /api/v1
  v2.context-path: /api/v2