### Common ###
module:
  name: WEB

spring:
  application:
    view-attachment-path: "http://localhost:8080/api/v1/partners/view-attachment/"
    name: Work Integrated Learning Management Application - WILMA

  profiles:
    active: dev # Set this as either dev or prod

  mail:
    # Credentials for the sendinblue smtp service
    site-email: projectwilma@mail.com
    host: smtp-relay.sendinblue.com
    port: 587
    username: wilmaproject.dev@gmail.com
    password: re9XBCi4b-tshUX

  http:
    multipart:
      upload-path: web/src/main/resources/uploads/

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB

api:
  v1.context-path: /api/v1
  v2.context-path: /api/v2